#!/bin/bash

# Backup script created on 2024-10-04_22-22-44

mkdir -p backups/api
cp 'backend/api/Dockerfile' 'backups/api/Dockerfile'
cp 'backend/api/nest-cli.json' 'backups/api/nest-cli.json'
cp 'backend/api/README.md' 'backups/api/README.md'
cp 'backend/api/package-lock.json' 'backups/api/package-lock.json'
cp 'backend/api/package.json' 'backups/api/package.json'
cp 'backend/api/tsconfig.build.json' 'backups/api/tsconfig.build.json'
cp 'backend/api/tsconfig.json' 'backups/api/tsconfig.json'
cp 'backend/api/docker-compose.yml' 'backups/api/docker-compose.yml'
mkdir -p backups/api/test
cp 'backend/api/test/app.e2e-spec.ts' 'backups/api/test/app.e2e-spec.ts'
cp 'backend/api/test/jest-e2e.json' 'backups/api/test/jest-e2e.json'
mkdir -p backups/api/dist
cp 'backend/api/dist/app.controller.js.map' 'backups/api/dist/app.controller.js.map'
cp 'backend/api/dist/app.module.d.ts' 'backups/api/dist/app.module.d.ts'
cp 'backend/api/dist/ormconfig.js.map' 'backups/api/dist/ormconfig.js.map'
cp 'backend/api/dist/main.js.map' 'backups/api/dist/main.js.map'
cp 'backend/api/dist/main.d.ts' 'backups/api/dist/main.d.ts'
cp 'backend/api/dist/app.controller.js' 'backups/api/dist/app.controller.js'
cp 'backend/api/dist/tsconfig.build.tsbuildinfo' 'backups/api/dist/tsconfig.build.tsbuildinfo'
cp 'backend/api/dist/app.module.js.map' 'backups/api/dist/app.module.js.map'
cp 'backend/api/dist/main.js' 'backups/api/dist/main.js'
cp 'backend/api/dist/app.service.js.map' 'backups/api/dist/app.service.js.map'
cp 'backend/api/dist/ormconfig.d.ts' 'backups/api/dist/ormconfig.d.ts'
cp 'backend/api/dist/app.controller.d.ts' 'backups/api/dist/app.controller.d.ts'
cp 'backend/api/dist/ormconfig.js' 'backups/api/dist/ormconfig.js'
cp 'backend/api/dist/app.module.js' 'backups/api/dist/app.module.js'
cp 'backend/api/dist/app.service.js' 'backups/api/dist/app.service.js'
cp 'backend/api/dist/app.service.d.ts' 'backups/api/dist/app.service.d.ts'
mkdir -p backups/api/dist/payments
cp 'backend/api/dist/payments/payments.module.d.ts' 'backups/api/dist/payments/payments.module.d.ts'
cp 'backend/api/dist/payments/payments.module.js' 'backups/api/dist/payments/payments.module.js'
cp 'backend/api/dist/payments/payments.service.js' 'backups/api/dist/payments/payments.service.js'
cp 'backend/api/dist/payments/payments.service.js.map' 'backups/api/dist/payments/payments.service.js.map'
cp 'backend/api/dist/payments/payments.module.js.map' 'backups/api/dist/payments/payments.module.js.map'
cp 'backend/api/dist/payments/payments.controller.js.map' 'backups/api/dist/payments/payments.controller.js.map'
cp 'backend/api/dist/payments/payments.controller.d.ts' 'backups/api/dist/payments/payments.controller.d.ts'
cp 'backend/api/dist/payments/payments.controller.js' 'backups/api/dist/payments/payments.controller.js'
cp 'backend/api/dist/payments/payments.service.d.ts' 'backups/api/dist/payments/payments.service.d.ts'
mkdir -p backups/api/dist/payments/dto
cp 'backend/api/dist/payments/dto/create-payment.dto.js' 'backups/api/dist/payments/dto/create-payment.dto.js'
cp 'backend/api/dist/payments/dto/create-payment.dto.js.map' 'backups/api/dist/payments/dto/create-payment.dto.js.map'
cp 'backend/api/dist/payments/dto/create-payment.dto.d.ts' 'backups/api/dist/payments/dto/create-payment.dto.d.ts'
mkdir -p backups/api/dist/auth
cp 'backend/api/dist/auth/auth.service.d.ts' 'backups/api/dist/auth/auth.service.d.ts'
cp 'backend/api/dist/auth/auth.service.js.map' 'backups/api/dist/auth/auth.service.js.map'
cp 'backend/api/dist/auth/auth.module.js' 'backups/api/dist/auth/auth.module.js'
cp 'backend/api/dist/auth/auth.service.js' 'backups/api/dist/auth/auth.service.js'
cp 'backend/api/dist/auth/auth.controller.js' 'backups/api/dist/auth/auth.controller.js'
cp 'backend/api/dist/auth/auth.controller.d.ts' 'backups/api/dist/auth/auth.controller.d.ts'
cp 'backend/api/dist/auth/auth.module.d.ts' 'backups/api/dist/auth/auth.module.d.ts'
cp 'backend/api/dist/auth/auth.module.js.map' 'backups/api/dist/auth/auth.module.js.map'
cp 'backend/api/dist/auth/auth.controller.js.map' 'backups/api/dist/auth/auth.controller.js.map'
mkdir -p backups/api/dist/auth/dto
cp 'backend/api/dist/auth/dto/login.dto.js.map' 'backups/api/dist/auth/dto/login.dto.js.map'
cp 'backend/api/dist/auth/dto/register.dto.d.ts' 'backups/api/dist/auth/dto/register.dto.d.ts'
cp 'backend/api/dist/auth/dto/password-reset.dto.d.ts' 'backups/api/dist/auth/dto/password-reset.dto.d.ts'
cp 'backend/api/dist/auth/dto/register.dto.js' 'backups/api/dist/auth/dto/register.dto.js'
cp 'backend/api/dist/auth/dto/password-reset.dto.js' 'backups/api/dist/auth/dto/password-reset.dto.js'
cp 'backend/api/dist/auth/dto/login.dto.js' 'backups/api/dist/auth/dto/login.dto.js'
cp 'backend/api/dist/auth/dto/login.dto.d.ts' 'backups/api/dist/auth/dto/login.dto.d.ts'
cp 'backend/api/dist/auth/dto/register.dto.js.map' 'backups/api/dist/auth/dto/register.dto.js.map'
cp 'backend/api/dist/auth/dto/password-reset.dto.js.map' 'backups/api/dist/auth/dto/password-reset.dto.js.map'
mkdir -p backups/api/dist/auth/strategies
cp 'backend/api/dist/auth/strategies/jwt.strategy.js.map' 'backups/api/dist/auth/strategies/jwt.strategy.js.map'
cp 'backend/api/dist/auth/strategies/jwt.strategy.d.ts' 'backups/api/dist/auth/strategies/jwt.strategy.d.ts'
cp 'backend/api/dist/auth/strategies/jwt.strategy.js' 'backups/api/dist/auth/strategies/jwt.strategy.js'
mkdir -p backups/api/dist/auth/guards
cp 'backend/api/dist/auth/guards/jwt-auth.guard.js' 'backups/api/dist/auth/guards/jwt-auth.guard.js'
cp 'backend/api/dist/auth/guards/jwt-auth.guard.js.map' 'backups/api/dist/auth/guards/jwt-auth.guard.js.map'
cp 'backend/api/dist/auth/guards/jwt-auth.guard.d.ts' 'backups/api/dist/auth/guards/jwt-auth.guard.d.ts'
mkdir -p backups/api/dist/api-keys
cp 'backend/api/dist/api-keys/api-keys.module.d.ts' 'backups/api/dist/api-keys/api-keys.module.d.ts'
cp 'backend/api/dist/api-keys/api-keys.service.js.map' 'backups/api/dist/api-keys/api-keys.service.js.map'
cp 'backend/api/dist/api-keys/api-keys.module.js' 'backups/api/dist/api-keys/api-keys.module.js'
cp 'backend/api/dist/api-keys/api-keys.controller.js.map' 'backups/api/dist/api-keys/api-keys.controller.js.map'
cp 'backend/api/dist/api-keys/api-keys.module.js.map' 'backups/api/dist/api-keys/api-keys.module.js.map'
cp 'backend/api/dist/api-keys/api-keys.controller.js' 'backups/api/dist/api-keys/api-keys.controller.js'
cp 'backend/api/dist/api-keys/api-keys.controller.d.ts' 'backups/api/dist/api-keys/api-keys.controller.d.ts'
cp 'backend/api/dist/api-keys/api-keys.service.d.ts' 'backups/api/dist/api-keys/api-keys.service.d.ts'
cp 'backend/api/dist/api-keys/api-keys.service.js' 'backups/api/dist/api-keys/api-keys.service.js'
mkdir -p backups/api/dist/api-keys/dto
cp 'backend/api/dist/api-keys/dto/create-api-key.dto.js' 'backups/api/dist/api-keys/dto/create-api-key.dto.js'
cp 'backend/api/dist/api-keys/dto/create-api-key.dto.js.map' 'backups/api/dist/api-keys/dto/create-api-key.dto.js.map'
cp 'backend/api/dist/api-keys/dto/create-api-key.dto.d.ts' 'backups/api/dist/api-keys/dto/create-api-key.dto.d.ts'
mkdir -p backups/api/dist/common
mkdir -p backups/api/dist/common/dto
cp 'backend/api/dist/common/dto/base-user.dto.js' 'backups/api/dist/common/dto/base-user.dto.js'
cp 'backend/api/dist/common/dto/base-user.dto.d.ts' 'backups/api/dist/common/dto/base-user.dto.d.ts'
cp 'backend/api/dist/common/dto/base-user.dto.js.map' 'backups/api/dist/common/dto/base-user.dto.js.map'
mkdir -p backups/api/dist/common/filters
cp 'backend/api/dist/common/filters/all-exceptions.filter.js.map' 'backups/api/dist/common/filters/all-exceptions.filter.js.map'
cp 'backend/api/dist/common/filters/all-exceptions.filter.js' 'backups/api/dist/common/filters/all-exceptions.filter.js'
cp 'backend/api/dist/common/filters/all-exceptions.filter.d.ts' 'backups/api/dist/common/filters/all-exceptions.filter.d.ts'
mkdir -p backups/api/dist/common/interceptors
cp 'backend/api/dist/common/interceptors/logging.interceptor.js.map' 'backups/api/dist/common/interceptors/logging.interceptor.js.map'
cp 'backend/api/dist/common/interceptors/logging.interceptor.d.ts' 'backups/api/dist/common/interceptors/logging.interceptor.d.ts'
cp 'backend/api/dist/common/interceptors/logging.interceptor.js' 'backups/api/dist/common/interceptors/logging.interceptor.js'
mkdir -p backups/api/dist/users
cp 'backend/api/dist/users/users.service.d.ts' 'backups/api/dist/users/users.service.d.ts'
cp 'backend/api/dist/users/users.controller.d.ts' 'backups/api/dist/users/users.controller.d.ts'
cp 'backend/api/dist/users/users.module.d.ts' 'backups/api/dist/users/users.module.d.ts'
cp 'backend/api/dist/users/users.controller.js.map' 'backups/api/dist/users/users.controller.js.map'
cp 'backend/api/dist/users/users.service.js.map' 'backups/api/dist/users/users.service.js.map'
cp 'backend/api/dist/users/users.service.js' 'backups/api/dist/users/users.service.js'
cp 'backend/api/dist/users/users.controller.js' 'backups/api/dist/users/users.controller.js'
cp 'backend/api/dist/users/users.module.js' 'backups/api/dist/users/users.module.js'
cp 'backend/api/dist/users/users.module.js.map' 'backups/api/dist/users/users.module.js.map'
mkdir -p backups/api/dist/teams
cp 'backend/api/dist/teams/teams.controller.js.map' 'backups/api/dist/teams/teams.controller.js.map'
cp 'backend/api/dist/teams/teams.service.js' 'backups/api/dist/teams/teams.service.js'
cp 'backend/api/dist/teams/teams.module.js.map' 'backups/api/dist/teams/teams.module.js.map'
cp 'backend/api/dist/teams/teams.controller.js' 'backups/api/dist/teams/teams.controller.js'
cp 'backend/api/dist/teams/teams.controller.d.ts' 'backups/api/dist/teams/teams.controller.d.ts'
cp 'backend/api/dist/teams/teams.service.js.map' 'backups/api/dist/teams/teams.service.js.map'
cp 'backend/api/dist/teams/teams.module.d.ts' 'backups/api/dist/teams/teams.module.d.ts'
cp 'backend/api/dist/teams/teams.module.js' 'backups/api/dist/teams/teams.module.js'
cp 'backend/api/dist/teams/teams.service.d.ts' 'backups/api/dist/teams/teams.service.d.ts'
mkdir -p backups/api/dist/teams/dto
cp 'backend/api/dist/teams/dto/create-team.dto.d.ts' 'backups/api/dist/teams/dto/create-team.dto.d.ts'
cp 'backend/api/dist/teams/dto/create-team.dto.js' 'backups/api/dist/teams/dto/create-team.dto.js'
cp 'backend/api/dist/teams/dto/create-team.dto.js.map' 'backups/api/dist/teams/dto/create-team.dto.js.map'
mkdir -p backups/api/dist/entities
cp 'backend/api/dist/entities/base.entity.d.ts' 'backups/api/dist/entities/base.entity.d.ts'
cp 'backend/api/dist/entities/team.entity.js' 'backups/api/dist/entities/team.entity.js'
cp 'backend/api/dist/entities/payment.entity.d.ts' 'backups/api/dist/entities/payment.entity.d.ts'
cp 'backend/api/dist/entities/user.entity.js.map' 'backups/api/dist/entities/user.entity.js.map'
cp 'backend/api/dist/entities/team.entity.d.ts' 'backups/api/dist/entities/team.entity.d.ts'
cp 'backend/api/dist/entities/base.entity.js' 'backups/api/dist/entities/base.entity.js'
cp 'backend/api/dist/entities/base.entity.js.map' 'backups/api/dist/entities/base.entity.js.map'
cp 'backend/api/dist/entities/user.entity.d.ts' 'backups/api/dist/entities/user.entity.d.ts'
cp 'backend/api/dist/entities/api-key.entity.d.ts' 'backups/api/dist/entities/api-key.entity.d.ts'
cp 'backend/api/dist/entities/user.entity.js' 'backups/api/dist/entities/user.entity.js'
cp 'backend/api/dist/entities/api-key.entity.js.map' 'backups/api/dist/entities/api-key.entity.js.map'
cp 'backend/api/dist/entities/api-key.entity.js' 'backups/api/dist/entities/api-key.entity.js'
cp 'backend/api/dist/entities/payment.entity.js' 'backups/api/dist/entities/payment.entity.js'
cp 'backend/api/dist/entities/payment.entity.js.map' 'backups/api/dist/entities/payment.entity.js.map'
cp 'backend/api/dist/entities/team.entity.js.map' 'backups/api/dist/entities/team.entity.js.map'
mkdir -p backups/api/src
cp 'backend/api/src/main.ts' 'backups/api/src/main.ts'
cp 'backend/api/src/app.service.ts' 'backups/api/src/app.service.ts'
cp 'backend/api/src/ormconfig.ts' 'backups/api/src/ormconfig.ts'
cp 'backend/api/src/app.module.ts' 'backups/api/src/app.module.ts'
cp 'backend/api/src/app.controller.spec.ts' 'backups/api/src/app.controller.spec.ts'
cp 'backend/api/src/app.controller.ts' 'backups/api/src/app.controller.ts'
mkdir -p backups/api/src/migrations
mkdir -p backups/api/src/migrations/version_1
mkdir -p backups/api/src/migrations/initial
mkdir -p backups/api/src/payments
cp 'backend/api/src/payments/payments.controller.ts' 'backups/api/src/payments/payments.controller.ts'
cp 'backend/api/src/payments/payments.module.ts' 'backups/api/src/payments/payments.module.ts'
cp 'backend/api/src/payments/payments.service.ts' 'backups/api/src/payments/payments.service.ts'
mkdir -p backups/api/src/payments/dto
cp 'backend/api/src/payments/dto/create-payment.dto.ts' 'backups/api/src/payments/dto/create-payment.dto.ts'
mkdir -p backups/api/src/auth
cp 'backend/api/src/auth/auth.controller.ts' 'backups/api/src/auth/auth.controller.ts'
cp 'backend/api/src/auth/auth.service.ts' 'backups/api/src/auth/auth.service.ts'
cp 'backend/api/src/auth/auth.module.ts' 'backups/api/src/auth/auth.module.ts'
mkdir -p backups/api/src/auth/dto
cp 'backend/api/src/auth/dto/login.dto.ts' 'backups/api/src/auth/dto/login.dto.ts'
cp 'backend/api/src/auth/dto/register.dto.ts' 'backups/api/src/auth/dto/register.dto.ts'
cp 'backend/api/src/auth/dto/password-reset.dto.ts' 'backups/api/src/auth/dto/password-reset.dto.ts'
mkdir -p backups/api/src/auth/strategies
cp 'backend/api/src/auth/strategies/jwt.strategy.ts' 'backups/api/src/auth/strategies/jwt.strategy.ts'
mkdir -p backups/api/src/auth/guards
cp 'backend/api/src/auth/guards/jwt-auth.guard.ts' 'backups/api/src/auth/guards/jwt-auth.guard.ts'
mkdir -p backups/api/src/api-keys
cp 'backend/api/src/api-keys/api-keys.controller.ts' 'backups/api/src/api-keys/api-keys.controller.ts'
cp 'backend/api/src/api-keys/api-keys.service.ts' 'backups/api/src/api-keys/api-keys.service.ts'
cp 'backend/api/src/api-keys/api-keys.module.ts' 'backups/api/src/api-keys/api-keys.module.ts'
mkdir -p backups/api/src/api-keys/dto
cp 'backend/api/src/api-keys/dto/create-api-key.dto.ts' 'backups/api/src/api-keys/dto/create-api-key.dto.ts'
mkdir -p backups/api/src/common
mkdir -p backups/api/src/common/dto
cp 'backend/api/src/common/dto/base-user.dto.ts' 'backups/api/src/common/dto/base-user.dto.ts'
mkdir -p backups/api/src/common/filters
cp 'backend/api/src/common/filters/all-exceptions.filter.ts' 'backups/api/src/common/filters/all-exceptions.filter.ts'
mkdir -p backups/api/src/common/interceptors
cp 'backend/api/src/common/interceptors/logging.interceptor.ts' 'backups/api/src/common/interceptors/logging.interceptor.ts'
mkdir -p backups/api/src/users
cp 'backend/api/src/users/users.service.ts' 'backups/api/src/users/users.service.ts'
cp 'backend/api/src/users/users.controller.ts' 'backups/api/src/users/users.controller.ts'
cp 'backend/api/src/users/users.module.ts' 'backups/api/src/users/users.module.ts'
mkdir -p backups/api/src/teams
cp 'backend/api/src/teams/teams.module.ts' 'backups/api/src/teams/teams.module.ts'
cp 'backend/api/src/teams/teams.service.ts' 'backups/api/src/teams/teams.service.ts'
cp 'backend/api/src/teams/teams.controller.ts' 'backups/api/src/teams/teams.controller.ts'
mkdir -p backups/api/src/teams/dto
cp 'backend/api/src/teams/dto/create-team.dto.ts' 'backups/api/src/teams/dto/create-team.dto.ts'
mkdir -p backups/api/src/entities
cp 'backend/api/src/entities/payment.entity.ts' 'backups/api/src/entities/payment.entity.ts'
cp 'backend/api/src/entities/user.entity.ts' 'backups/api/src/entities/user.entity.ts'
cp 'backend/api/src/entities/api-key.entity.ts' 'backups/api/src/entities/api-key.entity.ts'
cp 'backend/api/src/entities/team.entity.ts' 'backups/api/src/entities/team.entity.ts'
cp 'backend/api/src/entities/base.entity.ts' 'backups/api/src/entities/base.entity.ts'
